### ISSUE TITLE
Research User Logins (Driver & Admin)

### ISSUE THREAD

**Issue by sophsuan** [hack4impact-calpoly/veggie-rescue#10]
## Description
Look into how we can implement user logins for the application! We have two types of users: 1) Drivers 2) Admin. This issue is a little complicated because they will have very different versions of signing in. We may need to use a completely different method for each type of user to sign in. This task may seem a little complicated and not as fun as actual coding, but is a very important and necessary part of our development! 

#### Driver Side
- they will have a basic login screen with a 4 digit pin code
- Problems:
    1. It is only guaranteed that drivers will have wifi access at the start of the trip in headquarters. They may still need to login and get access to the app without wifi. We will probably need to locally store hashed passwords of some form for this.
    2. AWS Cognito may not support 4-digit pin logins. Would it be possible for us to do this through MongoDB backend as part of the user schema? Anything else out there that seems to fit our needs and is reasonably easy to implement? Let me know what you find!
![image](https://user-images.githubusercontent.com/47379998/150668540-7ac7ba33-54ae-41a1-b6ca-7ac11c527965.png)

#### Admin Side
- This would need more security. Admin's login would be closer to the typical email/password type. We could use AWS's Cognito? Google authentication? Any other option that looks good? Look for what would fit our needs most and wouldn't be too complicated to implement! 
![image](https://user-images.githubusercontent.com/47379998/150668554-52e0cb4c-0858-416e-b8c2-31d5345b73bd.png)

## Success Metrics Checklist
- [x] Addresses problems listed
- [x] A few suggestions for what you think would work best
- [x] Think about how we can accommodate for both user types in the same app without making it too complicated
- [x] No need for a PR for this task :) you can just tell me your findings in a message or a brief notion page with options and their pros/cons with some resources you thought were useful!

**Comment by Howl1935** [comment]
Here are my suggestions.  If this sounds good I am ready to begin implementation and get routes setup ASAP.

https://h4i.notion.site/User-Authentication-a975c15b92b44680815feeee2edc1366

Thanks!
