### ISSUE TITLE
Research - PWA

### ISSUE THREAD

**Issue by sophsuan** [hack4impact-calpoly/veggie-rescue#16]
## Description
This is a research task for you to look more into what exactly a progressive web app is! A unique challenge our application faces is that the users are not guaranteed access to internet while they are picking up produce from different areas. Our solution to this will be to implement a PWA for its ability to be installed locally as a native app with network independent capabilities (for the most part). Your task is to learn more about this technology that is new to most, if not all of us, and put together a brief and informative notion page for everyone to use as reference! :) 

Possible topics to include:
- What exactly is it?
- What are service workers?
- How do we set it up? What do we need to add to make everything work correctly?
- Pro/con?
- How does it work?
- Anything else you find may be helpful/interesting!!

## Setup
There is no code involved in this task, but your final result should be a notion page linked on our team notion! (ask PM (Travis Hawley) for notion access if needed)

## Success Metrics Checklist
- [x] Be comfortable with the basic parts of PWA relevant to our application (can take questions from others)
- [x] Notion page added to team page

## Helpful Resource
https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps

**Comment by SamuelSehnert** [comment]
Link to Doc: [Notion Page](https://www.notion.so/h4i/36d4acba6ff240228baffab99ed49f9e?v=d415f201baa84301babea2a6dc09771d&p=a948dff4eb8b472596f8a543d4508fe7)
