### ISSUE TITLE
[Driver] Create Area - Pickup Screen

### ISSUE THREAD

**Issue by sophsuan** [hack4impact-calpoly/veggie-rescue#35]
## Description
Create "Area - Pickup" screen component based on [Figma](https://www.figma.com/file/kyLwtYfyCsRiV2baLVhizB/Veggie-Rescue-UI?node-id=3%3A15). Try to use Tailwind for css if you can! Refer to [notion](https://h4i.notion.site/Tailwind-CSS-7b4dfea04aa64eba82fe4175fae5e612) as needed. Try to make it as close to Figma as you can!

## Setup
1. Make folder ```ComponentName``` in ```/frontend/src/components/```
2. Create ```ComponentName.tsx``` and ```ComponentName.css``` in folder
3. Goodluck! (Add your component to App.tsx to see your changes)

## Success Metrics Checklist
- [ ] Looks like Figma
- [ ] Use existing NavBar component from  #1 
- [ ] Responsive Screen Handling
- [ ] Populates 'Food types' options with dummy data array (to be replaced with backend data) ex. FoodType = ['Produce', 'Packaged'] 
- [ ] store user inputs as state variables
- [ ] Continue button console logs

![image](https://user-images.githubusercontent.com/47379998/152105387-4baf0464-3ddb-4562-b89a-eab6d10a114b.png)

**Comment by syafiqnazim** [comment]
Hi @sophsuan can I take this task?

**Comment by sophsuan** [comment]
@syafiqnazim Hi! Sorry but we're not accepting contributions from people outside the organization at the moment
